# Generated by forjar dist (do not edit)
{
  description = "Rust-native Infrastructure as Code";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        version = "VERSION";
        src = {
          "x86_64-linux" = pkgs.fetchurl {
            url = "https://github.com/paiml/forjar/releases/download/v${version}/forjar-${version}-x86_64-unknown-linux-gnu.tar.gz";
            sha256 = "PLACEHOLDER_CHECKSUM";
          };
          "aarch64-linux" = pkgs.fetchurl {
            url = "https://github.com/paiml/forjar/releases/download/v${version}/forjar-${version}-aarch64-unknown-linux-gnu.tar.gz";
            sha256 = "PLACEHOLDER_CHECKSUM";
          };
          "x86_64-darwin" = pkgs.fetchurl {
            url = "https://github.com/paiml/forjar/releases/download/v${version}/forjar-${version}-x86_64-apple-darwin.tar.gz";
            sha256 = "PLACEHOLDER_CHECKSUM";
          };
          "aarch64-darwin" = pkgs.fetchurl {
            url = "https://github.com/paiml/forjar/releases/download/v${version}/forjar-${version}-aarch64-apple-darwin.tar.gz";
            sha256 = "PLACEHOLDER_CHECKSUM";
          };
        }.${system} or (throw "unsupported system: ${system}");
      in {
        packages.default = pkgs.stdenv.mkDerivation {
          pname = "forjar";
          inherit version;
          inherit src;
          sourceRoot = ".";
          unpackPhase = "tar xzf $src";
          installPhase = ''
            mkdir -p $out/bin
            cp forjar $out/bin/
          '';
        };
      }
    );
}
