# forjar - Rust CLI Binary Makefile
# Generated by Pragmatic AI Labs MCP Agent Toolkit (pmat)

.PHONY: all check format lint test bench bench-update build build-release run clean install help coverage audit deny doc-test

# Default target: run all checks and build
all: format check lint test build

# Type check the code
check:
	cargo check

# Format code with rustfmt
format:
	cargo fmt --all

# Lint with clippy
lint:
	cargo clippy --all-targets -- -D warnings

# Run tests
test:
	cargo test

# Run benchmarks (Criterion, 95% confidence intervals)
bench:
	cargo bench

# Run benchmarks and update README table
bench-update:
	./scripts/update_bench_table.sh

# Build debug binary
build:
	cargo build

# Build release binary
build-release:
	cargo build --release

# Run the application
run:
	cargo run

# Clean build artifacts
clean:
	cargo clean

# Install the binary to cargo bin directory
install: build-release
	cargo install --path .

# Run coverage analysis
coverage:
	cargo llvm-cov --summary-only --fail-under-lines 95

# Run security audit
audit:
	cargo audit
	cargo deny check

# Run doc tests
doc-test:
	cargo test --doc

# Show help
help:
	@echo "forjar - Available targets:"
	@echo "  all           - Run format, check, lint, test, and build"
	@echo "  check         - Type check the code"
	@echo "  format        - Format code with rustfmt"
	@echo "  lint          - Run clippy linter"
	@echo "  test          - Run tests"
	@echo "  bench         - Run benchmarks"
	@echo "  build         - Build debug binary"
	@echo "  build-release - Build optimized release binary"
	@echo "  run           - Run the application"
	@echo "  clean         - Remove build artifacts"
	@echo "  install       - Install the binary"
	@echo "  coverage      - Run coverage analysis (95% minimum)"
	@echo "  audit         - Run security audit (cargo-audit + cargo-deny)"
	@echo "  doc-test      - Run documentation tests"
	@echo "  help          - Show this help message"