//! The MCP tool surface is declared ONCE, in `verb_table!` (paiml/forjar#371).
//!
//! `src/verb/spec.rs` argues that a capability must be declared once, because
//! `src/mcp/registry.rs` previously stated the same nine tools in four places
//! and "the compiler would not notice if you edited three". The repo then
//! carried two more statements of that surface under `docs/`, both outside the
//! compiler's reach and both wrong:
//!
//!   * `docs/mcp-schema.json` — a 23 KB snapshot regenerated by hand from a
//!     shell redirect written down in the book. Last refreshed at 1.20.1: it
//!     advertised 9 tools while the live surface was 12, missing
//!     `forjar_remediate`, `forjar_audit` and `forjar_workspace`, and its
//!     `forjar_lint` input schema had no `max_cyclomatic`.
//!   * `docs/book/src/87-mcp-registry-image.md` — a PUBLISHED book chapter
//!     (SUMMARY.md), staler still: `assert_eq!(schema["tool_count"], 9)`,
//!     `assert_eq!(registry.len(), 9)` and a nine-row tool table. Chapter 06 of
//!     the same book says twelve, so the book contradicted itself.
//!
//! The searches that missed the second file looked for the FILENAME
//! `mcp-schema`, which the Markdown never mentions. The defect is the CLASS —
//! a restatement of the verb table that nothing generates and nothing checks —
//! so the guard below is written against the class, not the path. Test (c) in
//! particular stays useful after the deletions: it goes red on the next
//! `verb_table!` row that lands while a book page still names the old count.
//!
//! `forjar verb list` and `forjar mcp --schema` are the live answers, derived
//! from `verbs()` through `schemars`, and cost nothing to keep true.
//!
//! Usage: cargo test --test falsification_mcp_surface_has_no_checked_in_copy

use std::path::{Path, PathBuf};

fn docs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("docs")
}

/// Every `*.json` under `docs/`, minus mdbook's build output.
///
/// `docs/book/book/` is untracked render output whose presence depends on
/// whether anyone ran `mdbook build` locally, so a guard that walked it would
/// pass or fail according to a developer's habits rather than the tree.
fn json_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            if p.ends_with("book/book") || p.file_name().is_some_and(|n| n == ".pmat") {
                continue;
            }
            json_files(&p, out);
        } else if p.extension().is_some_and(|x| x == "json") {
            out.push(p);
        }
    }
}

/// (a) REJECTION CRITERION: a checked-in snapshot of the MCP tool surface.
///
/// The predicate is the SHAPE, not the filename: a top-level object naming
/// `forjar-mcp` as its server and carrying a `tools` array is a copy of
/// `export_schema()` whatever it is called. That discriminates — the other four
/// JSON files under `docs/` are dogfood reports and defect lists, and none of
/// them matches.
#[test]
fn no_json_under_docs_restates_the_mcp_tool_surface() {
    let mut files = Vec::new();
    json_files(&docs_dir(), &mut files);
    assert!(
        !files.is_empty(),
        "found no JSON under docs/ at all — the guard would pass vacuously"
    );

    let snapshots: Vec<String> = files
        .iter()
        .filter(|p| {
            let Ok(text) = std::fs::read_to_string(p) else {
                return false;
            };
            let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) else {
                return false;
            };
            v.get("server").and_then(serde_json::Value::as_str) == Some("forjar-mcp")
                && v.get("tools").is_some_and(serde_json::Value::is_array)
        })
        .map(|p| p.display().to_string())
        .collect();

    assert!(
        snapshots.is_empty(),
        "these files are checked-in copies of the MCP tool surface: {snapshots:?}\n\
         Nothing generates them and nothing checks them, so they drift silently \
         and an integrator who generates a client from one gets a client that \
         disagrees with the server. `forjar mcp --schema` is the live answer."
    );
}

/// (b) REJECTION CRITERION: the instruction that manufactures the snapshot.
///
/// Deleting the file while the book still tells a reader to write it back is
/// half a fix — the next person who follows the documented step re-creates the
/// artifact, and this suite is green again the moment they do not commit it.
#[test]
fn the_book_does_not_tell_anyone_to_write_the_snapshot_back() {
    let cli = docs_dir().join("book").join("src").join("06-cli.md");
    let text = std::fs::read_to_string(&cli)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", cli.display()));

    assert!(
        !text.contains("> docs/mcp-schema.json"),
        "{} still redirects `forjar mcp --schema` into a checked-in file. The \
         command alone is the documentation; the redirect is what created the \
         stale copy.",
        cli.display()
    );
}

/// (c) REJECTION CRITERION, and the one that covers the class: a book page that
/// states a tool count for the MCP surface which the surface does not have.
///
/// This is the assertion the two deletions above cannot deliver. (a) matches
/// only JSON with a `tools` array, so a Markdown restatement — the form that
/// actually existed, and the worse of the two because it renders as a published
/// chapter — sails past it. This one is keyed to `verbs().len()`, so it also
/// fires on the next row added to `verb_table!` while a page still names the
/// old number.
#[test]
fn no_book_page_states_a_tool_count_the_surface_does_not_have() {
    let live = forjar::verb::verbs().len();
    assert!(live >= 12, "the verb table collapsed to {live} rows");

    let src = docs_dir().join("book").join("src");
    let mut pages: Vec<PathBuf> = std::fs::read_dir(&src)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", src.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "md"))
        .collect();
    pages.sort();
    assert!(!pages.is_empty(), "no book pages found — guard is vacuous");

    // Both spellings the repo actually used, as they appear in a Rust snippet a
    // reader would copy: `schema["tool_count"], N` and `registry.len(), N`.
    let patterns = [
        regex::Regex::new(r#"tool_count"\]\s*,\s*(\d+)"#).unwrap(),
        regex::Regex::new(r"registry\.len\(\)\s*,\s*(\d+)").unwrap(),
    ];

    let mut wrong: Vec<String> = Vec::new();
    for page in &pages {
        let Ok(text) = std::fs::read_to_string(page) else {
            continue;
        };
        for (n, line) in text.lines().enumerate() {
            for re in &patterns {
                for c in re.captures_iter(line) {
                    let stated: usize = c[1].parse().unwrap_or(usize::MAX);
                    if stated != live {
                        wrong.push(format!(
                            "{}:{}: states {stated}, surface has {live} — `{}`",
                            page.display(),
                            n + 1,
                            line.trim()
                        ));
                    }
                }
            }
        }
    }

    assert!(
        wrong.is_empty(),
        "book pages restate the MCP tool count and disagree with \
         `forjar::verb::verbs()`:\n  {}\n\
         A count typed into a document drifts; `forjar verb list` is the \
         authoritative set.",
        wrong.join("\n  ")
    );
}
