//! Tests: Misc.

use crate::core::types::ProvenanceEvent;
use crate::core::{codegen, executor, migrate, parser, planner, resolver, secrets, state, types};
use crate::transport;
use crate::tripwire::{anomaly, drift, eventlog, tracer};
use std::path::{Path, PathBuf};
use super::helpers::*;
use super::helpers_state::*;
use super::helpers_time::*;
use super::commands::*;

#[cfg(test)]
mod tests {
    use super::*;


    #[test]
    fn test_fj372_changes_since_flag() {
        let cmd = Commands::Status(StatusArgs {
            state_dir: PathBuf::from("state"),
            machine: None,
            json: false,
            file: None,
            summary: false,
            watch: None,
            stale: None,
            health: false,
            drift_details: false,
            timeline: false,
            changes_since: Some("abc123".to_string()),
            summary_by: None,
            prometheus: false,
            expired: None,
            count: false,
            format: None,
            anomalies: false,
            diff_from: None,
            resources_by_type: false,
            machines_only: false,
            stale_resources: false,
            health_threshold: None,
            json_lines: false,
            since: None,
            export: None,
            compact: false,
            alerts: false,
            diff_lock: None,
            compliance: None,
            histogram: false,
            dependency_health: false,
            top_failures: false,
            convergence_rate: false,
            drift_summary: false,
            resource_age: false,
            sla_report: false,
            compliance_report: None,
            mttr: false,
            trend: None,
            prediction: false,
            capacity: false,
            cost_estimate: false,
            staleness_report: None,
            health_score: false,
            executive_summary: false,
            audit_trail: false,
            resource_graph: false,
            drift_velocity: false,
            fleet_overview: false,
            machine_health: false,
            config_drift: false,
            convergence_time: false,
            resource_timeline: false,
            error_summary: false,
            security_posture: false,
            resource_cost: false,
            drift_forecast: false,
            pipeline_status: false,
            resource_dependencies: false,
            diagnostic: false,
            uptime: false,
            recommendations: false,
            machine_summary: false,
            change_frequency: false,
            lock_age: false,
            failed_since: None,
            hash_verify: false,
            resource_size: false,
            drift_details_all: false,
            last_apply_duration: false,
            config_hash: false,
            convergence_history: false,
            resource_inputs: false,
            drift_trend: false,
            failed_resources: false,
            resource_types_summary: false,
            resource_health: false,
            machine_health_summary: false,
            dependency_count: false,
            last_apply_status: false,
            resource_staleness: false,
            convergence_percentage: false,
            failed_count: false,
            drift_count: false,
            resource_duration: false,
            machine_resource_map: false,
            fleet_convergence: false,
            resource_hash: false,
            machine_drift_summary: false,
            apply_history_count: false,
            lock_file_count: false,
            resource_type_distribution: false,
            resource_apply_age: false,
            machine_uptime: false,
            resource_churn: false,
            last_drift_time: false,
            machine_resource_count: false,
            convergence_score: false,
            apply_success_rate: false,
            error_rate: false,
            fleet_health_summary: false, machine_convergence_history: false, drift_history: false, resource_failure_rate: false, machine_last_apply: false, fleet_drift_summary: false, resource_apply_duration: false, machine_resource_health: false, fleet_convergence_trend: false, resource_state_distribution: false, machine_apply_count: false, fleet_apply_history: false, resource_hash_changes: false, machine_uptime_estimate: false, fleet_resource_type_breakdown: false, resource_convergence_time: false,
                machine_drift_age: false,
                fleet_failed_resources: false,
                resource_dependency_health: false,
                machine_resource_age_distribution: false,
                fleet_convergence_velocity: false, resource_failure_correlation: false,
                machine_resource_churn_rate: false, fleet_resource_staleness: false, machine_convergence_trend: false, machine_capacity_utilization: false, fleet_configuration_entropy: false, machine_resource_freshness: false, machine_error_budget: false, fleet_compliance_score: false, machine_mean_time_to_recovery: false, machine_resource_dependency_health: false, fleet_resource_type_health: false, machine_resource_convergence_rate: false, machine_resource_failure_correlation: false, fleet_resource_age_distribution: false, machine_resource_rollback_readiness: false, machine_resource_health_trend: false, fleet_resource_drift_velocity: false, machine_resource_apply_success_trend: false, machine_resource_mttr_estimate: false, fleet_resource_convergence_forecast: false, machine_resource_error_budget_forecast: false, machine_resource_dependency_lag: false, fleet_resource_dependency_lag: false, machine_resource_config_drift_rate: false, machine_resource_convergence_lag: false, fleet_resource_convergence_lag: false, machine_resource_dependency_depth: false, machine_resource_convergence_velocity: false, fleet_resource_convergence_velocity: false, machine_resource_failure_recurrence: false, machine_resource_drift_frequency: false, fleet_resource_drift_frequency: false, machine_resource_apply_duration_trend: false, machine_resource_convergence_streak: false, fleet_resource_convergence_streak: false, machine_resource_error_distribution: false, machine_resource_drift_age: false, fleet_resource_drift_age: false, machine_resource_recovery_rate: false, machine_resource_drift_velocity: false, fleet_resource_recovery_rate: false, machine_resource_convergence_efficiency: false, machine_resource_apply_frequency: false, fleet_resource_health_score: false, machine_resource_staleness_index: false, machine_resource_drift_recurrence: false, fleet_resource_drift_heatmap: false, machine_resource_convergence_trend_p90: false, machine_resource_drift_age_hours: false, fleet_resource_convergence_percentile: false, machine_resource_error_rate: false, machine_resource_convergence_gap: false, fleet_resource_error_distribution: false, machine_resource_convergence_stability: false, machine_resource_apply_latency_p95: false, fleet_resource_security_posture_score: false, fleet_apply_success_rate_trend: false, machine_resource_drift_flapping: false, fleet_resource_type_drift_heatmap: false, machine_ssh_connection_health: false, lock_file_staleness_report: false, fleet_transport_method_summary: false, fleet_state_churn_analysis: false, config_maturity_score: false, fleet_capacity_utilization: false,
            fleet_drift_velocity_trend: false,
            machine_convergence_window: false,
            fleet_resource_age_histogram: false,
        });
        match cmd {
            Commands::Status(StatusArgs { changes_since, .. }) => {
                assert_eq!(changes_since, Some("abc123".to_string()));
            }
            _ => panic!("expected Status"),
        }
    }


    #[test]
    fn test_fj375_critical_path_flag() {
        let cmd = Commands::Graph(GraphArgs {
            file: PathBuf::from("f.yaml"),
            format: "mermaid".to_string(),
            machine: None,
            group: None,
            affected: None,
            critical_path: true,
            reverse: false,
            depth: None,
            cluster: false,
            orphans: false,
            stats: false,
            json_output: false,
            highlight: None,
            prune: None,
            layers: false,
            critical_resources: false,
            weight: false,
            subgraph: None,
            impact_radius: None,
            dependency_matrix: false,
            hotspots: false,
            timeline_graph: false,
            what_if: None,
            blast_radius: None,
            change_impact: None,
            resource_types: false,
            topological_levels: false,
            execution_order: false,
            security_boundaries: false,
            resource_age: false,
            parallel_groups: false,
            critical_chain: false,
            dependency_depth: false,
            orphan_detection: false,
            cross_machine_deps: false,
            machine_groups: false,
            resource_clusters: false,
            fan_out: false,
            leaf_resources: false,
            reverse_deps: false,
            depth_first: false,
            breadth_first: false,
            subgraph_stats: false,
            dependency_count: false,
            root_resources: false,
            edge_list: false,
            connected_components: false,
            adjacency_matrix: false,
            longest_path: false,
            in_degree: false,
            out_degree: false,
            density: false,
            topological_sort: false,
            critical_path_resources: false,
            sink_resources: false,
            bipartite_check: false,
            strongly_connected: false,
            dependency_matrix_csv: false, resource_weight: false, dependency_depth_per_resource: false, resource_fanin: false, isolated_subgraphs: false, resource_dependency_chain: None, bottleneck_resources: false, critical_dependency_path: false, resource_depth_histogram: false, resource_coupling_score: false, resource_change_frequency: false,
                resource_impact_score: false,
                resource_stability_score: false,
                resource_dependency_fanout: false, resource_dependency_weight: false, resource_dependency_bottleneck: false, resource_type_clustering: false, resource_dependency_cycle_risk: false, resource_impact_radius: false, resource_dependency_health_map: false, resource_change_propagation: false, resource_dependency_depth_analysis: false, resource_dependency_fan_analysis: false, resource_dependency_isolation_score: false, resource_dependency_stability_score: false, resource_dependency_critical_path_length: false, resource_dependency_redundancy_score: false, resource_dependency_centrality_score: false, resource_dependency_bridge_detection: false, resource_dependency_cluster_coefficient: false, resource_dependency_modularity_score: false, resource_dependency_diameter: false, resource_dependency_eccentricity: false, resource_dependency_density: false, resource_dependency_transitivity: false, resource_dependency_fan_out: false, resource_dependency_fan_in: false, resource_dependency_path_count: false, resource_dependency_articulation_points: false, resource_dependency_longest_path: false, resource_dependency_strongly_connected: false, resource_dependency_topological_depth: false, resource_dependency_weak_links: false, resource_dependency_minimum_cut: false, resource_dependency_dominator_tree: false, resource_dependency_resilience_score: false, resource_dependency_pagerank: false, resource_dependency_betweenness_centrality: false, resource_dependency_closure_size: false, resource_dependency_eccentricity_map: false, resource_dependency_diameter_path: false, resource_dependency_bridge_criticality: false, resource_dependency_conditional_subgraph: false, resource_dependency_parallel_groups: false, resource_dependency_execution_cost: false, resource_recipe_expansion_map: false, resource_dependency_critical_chain_path: false, resource_apply_order_simulation: false, resource_provenance_summary: false,
            resource_dependency_risk_score: false,
            resource_dependency_layering: false,
        });
        match cmd {
            Commands::Graph(GraphArgs { critical_path, .. }) => assert!(critical_path),
            _ => panic!("expected Graph"),
        }
    }


    #[test]
    fn test_fj376_summary_by_flag() {
        let cmd = Commands::Status(StatusArgs {
            state_dir: PathBuf::from("state"),
            machine: None,
            json: false,
            file: None,
            summary: false,
            watch: None,
            stale: None,
            health: false,
            drift_details: false,
            timeline: false,
            changes_since: None,
            summary_by: Some("machine".to_string()),
            prometheus: false,
            expired: None,
            count: false,
            format: None,
            anomalies: false,
            diff_from: None,
            resources_by_type: false,
            machines_only: false,
            stale_resources: false,
            health_threshold: None,
            json_lines: false,
            since: None,
            export: None,
            compact: false,
            alerts: false,
            diff_lock: None,
            compliance: None,
            histogram: false,
            dependency_health: false,
            top_failures: false,
            convergence_rate: false,
            drift_summary: false,
            resource_age: false,
            sla_report: false,
            compliance_report: None,
            mttr: false,
            trend: None,
            prediction: false,
            capacity: false,
            cost_estimate: false,
            staleness_report: None,
            health_score: false,
            executive_summary: false,
            audit_trail: false,
            resource_graph: false,
            drift_velocity: false,
            fleet_overview: false,
            machine_health: false,
            config_drift: false,
            convergence_time: false,
            resource_timeline: false,
            error_summary: false,
            security_posture: false,
            resource_cost: false,
            drift_forecast: false,
            pipeline_status: false,
            resource_dependencies: false,
            diagnostic: false,
            uptime: false,
            recommendations: false,
            machine_summary: false,
            change_frequency: false,
            lock_age: false,
            failed_since: None,
            hash_verify: false,
            resource_size: false,
            drift_details_all: false,
            last_apply_duration: false,
            config_hash: false,
            convergence_history: false,
            resource_inputs: false,
            drift_trend: false,
            failed_resources: false,
            resource_types_summary: false,
            resource_health: false,
            machine_health_summary: false,
            dependency_count: false,
            last_apply_status: false,
            resource_staleness: false,
            convergence_percentage: false,
            failed_count: false,
            drift_count: false,
            resource_duration: false,
            machine_resource_map: false,
            fleet_convergence: false,
            resource_hash: false,
            machine_drift_summary: false,
            apply_history_count: false,
            lock_file_count: false,
            resource_type_distribution: false,
            resource_apply_age: false,
            machine_uptime: false,
            resource_churn: false,
            last_drift_time: false,
            machine_resource_count: false,
            convergence_score: false,
            apply_success_rate: false,
            error_rate: false,
            fleet_health_summary: false, machine_convergence_history: false, drift_history: false, resource_failure_rate: false, machine_last_apply: false, fleet_drift_summary: false, resource_apply_duration: false, machine_resource_health: false, fleet_convergence_trend: false, resource_state_distribution: false, machine_apply_count: false, fleet_apply_history: false, resource_hash_changes: false, machine_uptime_estimate: false, fleet_resource_type_breakdown: false, resource_convergence_time: false,
                machine_drift_age: false,
                fleet_failed_resources: false,
                resource_dependency_health: false,
                machine_resource_age_distribution: false,
                fleet_convergence_velocity: false, resource_failure_correlation: false,
                machine_resource_churn_rate: false, fleet_resource_staleness: false, machine_convergence_trend: false, machine_capacity_utilization: false, fleet_configuration_entropy: false, machine_resource_freshness: false, machine_error_budget: false, fleet_compliance_score: false, machine_mean_time_to_recovery: false, machine_resource_dependency_health: false, fleet_resource_type_health: false, machine_resource_convergence_rate: false, machine_resource_failure_correlation: false, fleet_resource_age_distribution: false, machine_resource_rollback_readiness: false, machine_resource_health_trend: false, fleet_resource_drift_velocity: false, machine_resource_apply_success_trend: false, machine_resource_mttr_estimate: false, fleet_resource_convergence_forecast: false, machine_resource_error_budget_forecast: false, machine_resource_dependency_lag: false, fleet_resource_dependency_lag: false, machine_resource_config_drift_rate: false, machine_resource_convergence_lag: false, fleet_resource_convergence_lag: false, machine_resource_dependency_depth: false, machine_resource_convergence_velocity: false, fleet_resource_convergence_velocity: false, machine_resource_failure_recurrence: false, machine_resource_drift_frequency: false, fleet_resource_drift_frequency: false, machine_resource_apply_duration_trend: false, machine_resource_convergence_streak: false, fleet_resource_convergence_streak: false, machine_resource_error_distribution: false, machine_resource_drift_age: false, fleet_resource_drift_age: false, machine_resource_recovery_rate: false, machine_resource_drift_velocity: false, fleet_resource_recovery_rate: false, machine_resource_convergence_efficiency: false, machine_resource_apply_frequency: false, fleet_resource_health_score: false, machine_resource_staleness_index: false, machine_resource_drift_recurrence: false, fleet_resource_drift_heatmap: false, machine_resource_convergence_trend_p90: false, machine_resource_drift_age_hours: false, fleet_resource_convergence_percentile: false, machine_resource_error_rate: false, machine_resource_convergence_gap: false, fleet_resource_error_distribution: false, machine_resource_convergence_stability: false, machine_resource_apply_latency_p95: false, fleet_resource_security_posture_score: false, fleet_apply_success_rate_trend: false, machine_resource_drift_flapping: false, fleet_resource_type_drift_heatmap: false, machine_ssh_connection_health: false, lock_file_staleness_report: false, fleet_transport_method_summary: false, fleet_state_churn_analysis: false, config_maturity_score: false, fleet_capacity_utilization: false,
            fleet_drift_velocity_trend: false,
            machine_convergence_window: false,
            fleet_resource_age_histogram: false,
        });
        match cmd {
            Commands::Status(StatusArgs { summary_by, .. }) => {
                assert_eq!(summary_by, Some("machine".to_string()));
            }
            _ => panic!("expected Status"),
        }
    }


    #[test]
    fn test_fj377_max_failures_flag() {
        let cmd = Commands::Apply(ApplyArgs {
            file: PathBuf::from("f.yaml"),
            state_dir: PathBuf::from("state"),
            machine: None,
            resource: None,
            tag: None,
            group: None,
            force: false,
            dry_run: false,
            no_tripwire: false,
            params: vec![],
            auto_commit: false,
            timeout: None,
            json: false,
            env_file: None,
            workspace: None,
            check: false,
            report: false,
            force_unlock: false,
            output: None,
            progress: false,
            timing: false,
            retry: 0,
            yes: false,
            parallel: false,
            resource_timeout: None,
            rollback_on_failure: false,
            max_parallel: None,
            notify: None,
            subset: None,
            confirm_destructive: false,
            backup: false,
            exclude: None,
            sequential: false,
            diff_only: false,
            notify_slack: None,
            cost_limit: None,
            preview: false,
            tag_filter: None,
            output_scripts: None,
            resume: false,
            confirm: false,
            max_failures: Some(3),
            rate_limit: None,
            labels: vec![],
            plan_file: None,
            notify_email: None,
            skip: None,
            snapshot_before: None,
            concurrency: None,
            webhook_before: None,
            rollback_snapshot: None,
            retry_delay: None,
            tags: vec![],
            log_file: None,
            comment: None,
            only_changed: false,
            pre_script: None,
            dry_run_json: false,
            notify_webhook: None,
            post_script: None,
            approval_required: false,
            canary_percent: None,
            schedule: None,
            env_name: None,
            dry_run_diff: false,
            notify_pagerduty: None,
            batch_size: None,
            notify_teams: None,
            abort_on_drift: false,
            dry_run_summary: false,
            notify_discord: None,
            rollback_on_threshold: None,
            metrics_port: None,
            notify_opsgenie: None,
            circuit_breaker: None,
            require_approval: None,
            notify_datadog: None,
            change_window: None,
            canary_machine: None,
            notify_newrelic: None,
            max_duration: None,
            notify_grafana: None,
            rate_limit_resources: None,
            checkpoint_interval: None,
            notify_victorops: None,
            blue_green: None,
            dry_run_cost: false,
            notify_msteams_adaptive: None,
            progressive: None,
            approval_webhook: None,
            notify_incident: None,
            sign_off: None,
            notify_sns: None,
            telemetry_endpoint: None,
            runbook: None,
            notify_pubsub: None,
            fleet_strategy: None,
            pre_check: None,
            notify_eventbridge: None,
            dry_run_graph: false,
            post_check: None,
            notify_kafka: None,
            max_retries: None,
            rollback_window: None,
            notify_azure_servicebus: None,
            approval_timeout: None,
            pre_flight: None,
            notify_gcp_pubsub_v2: None,
            checkpoint: None,
            post_flight: None,
            notify_rabbitmq: None,
            gate: None,
            notify_nats: None,
            dry_run_verbose: false,
            explain: false,
            notify_mqtt: None,
            confirmation_message: None,
            summary_only: false,
            notify_redis: None,
            notify_amqp: None,
            pre_apply_hook: None,
            resource_filter: None,
            notify_stomp: None,
            post_apply_hook: None,
            dry_run_shell: false,
            notify_zeromq: None,
            canary_resource: None,
            timeout_per_resource: None,
            notify_grpc: None,
            skip_unchanged: false,
            retry_backoff: None,
            notify_sqs: None,
            plan_output_file: None,
            resource_priority: vec![],
            apply_window: None,
            fail_fast_machine: false,
            notify_mattermost: None,
            cooldown: None,
            exclude_machine: None,
            notify_ntfy: None,
            only_machine: None,
            notify_webhook_headers: None,
            notify_log: None,
        notify_exec: None,
        notify_file: None,
        notify_json: false,
            notify_slack_webhook: None,
            notify_telegram: None,
            notify_webhook_v2: None, notify_discord_webhook: None, notify_teams_webhook: None, notify_slack_blocks: None, notify_custom_template: None, notify_custom_webhook: None, notify_custom_headers: None, notify_custom_json: None, notify_custom_filter: None, notify_custom_retry: None, notify_custom_transform: None, notify_custom_batch: None, notify_custom_deduplicate: None, notify_custom_throttle: None, notify_custom_aggregate: None, notify_custom_priority: None, notify_custom_routing: None, notify_custom_dedup_window: None, notify_custom_rate_limit: None, notify_custom_backoff: None, notify_custom_circuit_breaker: None, notify_custom_dead_letter: None, notify_custom_escalation: None, notify_custom_correlation: None, notify_custom_sampling: None, notify_custom_digest: None, notify_custom_severity_filter: None,
        });
        match cmd {
            Commands::Apply(ApplyArgs { max_failures, .. }) => assert_eq!(max_failures, Some(3)),
            _ => panic!("expected Apply"),
        }
    }

    // ── Phase 24: Enterprise & Scale (FJ-380→FJ-387) ──

}
