#!/usr/bin/env bash
# Dogfood gate C — the transport surface, measured rather than declared.
#
# Exit code is the gate. The only line a caller must read is the final
# `GATE C PASS|FAIL <detail>`.
#
# paiml/forjar#288 is why this gate exists in this shape: a derived transport
# tree that nothing routed to stayed green in every parity test while being
# reachable by no user. A parity test compares transports TO EACH OTHER, so it
# is structurally incapable of noticing that none of them is reachable.
# Agreement is not reachability. Every row below is therefore produced by
# ASKING THE RUNNING ARTIFACT — `--help` on the built binary, a real
# `tools/list` over stdio, a real `GET /v1/verbs` against a listening socket —
# and never by reading a list out of a file.
#
# The two columns that carry the finding:
#
#   declared  the name is in the transport's declaration source: the clap tree
#             for CLI, `verb list` (the unified registry) for MCP and HTTP.
#   live      the transport actually answered for it.
#
# `declared != live` in either direction is the defect. `declared,no-live` is a
# capability the docs promise and the binary does not have; `no-declared,live`
# is a capability shipping with nothing governing it.
#
# docs/audits/surface_audit.csv is the committed snapshot. It is GENERATED by
# this script (`FORJAR_DOGFOOD_WRITE=1 bash scripts/dogfood/surface.sh`) and
# never hand-edited: a surface list written by hand is a second source of truth
# that cannot fail. On an ordinary run the script re-derives it and diffs; a
# difference is a surface change, and it must be committed deliberately.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

CSV="docs/audits/surface_audit.csv"

# Vacuity floors — today's counts. A gate that measured an empty surface would
# report "every declared name is live" and be telling the truth about nothing.
# These may RISE as the surface grows; a fall is a finding, not a threshold to
# lower.
MIN_CLI=211
MIN_MCP=12
MIN_HTTP=12

fail() {
  echo "GATE C FAIL $1"
  exit 1
}

BIN="$(bash "$(dirname "${BASH_SOURCE[0]}")/lib/binary.sh")"

derived="$(mktemp)"
trap 'rm -f "$derived"' EXIT

# ---------------------------------------------------------------- derivation
#
# In python because the work is process orchestration and JSON, not text
# munging: an MCP handshake is two framed requests on one stdin, and the HTTP
# arm has to own a child process and kill it on every exit path.
python3 - "$BIN" "$derived" <<'PY'
import json, os, selectors, socket, subprocess, sys, time, urllib.error, urllib.request

BIN, OUT = sys.argv[1], sys.argv[2]
rows = []


def run(args, **kw):
    return subprocess.run([BIN] + args, capture_output=True, text=True, **kw)


def mcp_request(binary, request, want_id, timeout=60):
    """One MCP round trip over stdio, returning the reply with id == want_id.

    `forjar mcp` is a SERVER: it does not exit when stdin closes, so
    `subprocess.run(input=...)` blocks until the timeout and reports the probe
    as absent — a live transport recorded as missing. The server is therefore
    spawned, handed the handshake plus the request, read from until the awaited
    id arrives, and then killed. Raises RuntimeError if it never answers, so an
    absent transport and a broken one are distinguishable by the caller.
    """
    init = {"jsonrpc": "2.0", "id": 1, "method": "initialize",
            "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                       "clientInfo": {"name": "forjar-dogfood", "version": "1"}}}
    proc = subprocess.Popen([binary, "mcp"], stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                            text=True, bufsize=1)
    try:
        proc.stdin.write(json.dumps(init) + "\n" + json.dumps(request) + "\n")
        proc.stdin.flush()
        sel = selectors.DefaultSelector()
        sel.register(proc.stdout, selectors.EVENT_READ)
        deadline = time.time() + timeout
        while time.time() < deadline:
            if not sel.select(timeout=max(0.0, deadline - time.time())):
                continue
            line = proc.stdout.readline()
            if not line:
                raise RuntimeError(f"`{binary} mcp` closed stdout before answering id={want_id}")
            try:
                msg = json.loads(line)
            except ValueError:
                continue
            if msg.get("id") == want_id:
                return msg
        raise RuntimeError(f"`{binary} mcp` did not answer id={want_id} within {timeout}s")
    finally:
        proc.kill()
        proc.wait(timeout=30)


# ------------------------------------------------------------------- CLI
#
# The declaration is the clap tree: whatever `--help` lists is what forjar
# tells a user it can do. The liveness probe is `<path> --help` exiting 0 —
# a name clap lists but cannot route is the #288 failure at the CLI level.
# `help` is clap's own builtin and not part of forjar's surface.
def subcommands(text):
    out, inside = [], False
    for line in text.splitlines():
        if line.startswith("Commands:"):
            inside = True
            continue
        if inside and not line.strip():
            continue
        if inside and line[:1] not in (" ", "\t"):
            inside = False
            continue
        if inside and line.startswith("  ") and line[2:3] not in (" ", "-"):
            name = line.strip().split()[0]
            if name != "help":
                out.append(name)
    return out


top = run(["--help"])
if top.returncode != 0:
    sys.exit(f"`forjar --help` exited {top.returncode}: the binary has no surface to measure")
for cmd in subcommands(top.stdout + top.stderr):
    r = run([cmd, "--help"])
    rows.append(("cli", "command", cmd, "yes", "yes" if r.returncode == 0 else "no"))
    for sub in subcommands(r.stdout + r.stderr):
        r2 = run([cmd, sub, "--help"])
        rows.append(("cli", "subcommand", f"{cmd} {sub}", "yes",
                     "yes" if r2.returncode == 0 else "no"))

# ------------------------------------------------- the unified verb registry
#
# One registry feeds both MCP and HTTP, so it is read once and each transport
# is then asked whether it actually serves what the registry declares.
vl = run(["verb", "list"])
if vl.returncode != 0:
    sys.exit(f"`forjar verb list` exited {vl.returncode}")
verbs = [v for v in vl.stdout.split() if v]

# ------------------------------------------------------------------- MCP
#
# A LIVE `tools/list` over stdio, not the `mcp` feature flag and not a count
# from the source. The release binary ships `forjar mcp` in the default build;
# were it absent, the row would read `absent` and carry the command that
# proves it — see the `mcp_absent` branch.
mcp_live = set()
proving = f"printf '<initialize>\\n<tools/list>\\n' | {BIN} mcp"
mcp_absent = None
try:
    reply = mcp_request(BIN, {"jsonrpc": "2.0", "id": 2, "method": "tools/list",
                              "params": {}}, want_id=2)
    mcp_live = {t["name"] for t in reply.get("result", {}).get("tools", [])}
except RuntimeError as e:
    mcp_absent = str(e)

if mcp_absent is not None:
    rows.append(("mcp", "transport", "ABSENT", "no", f"absent: {proving}"))
else:
    for v in verbs:
        rows.append(("mcp", "tool", f"forjar_{v}", "yes",
                     "yes" if f"forjar_{v}" in mcp_live else "no"))
    for extra in sorted(mcp_live - {f"forjar_{v}" for v in verbs}):
        rows.append(("mcp", "tool", extra, "no", "yes"))

# ------------------------------------------------------------------ HTTP
#
# A router does exist — `forjar verb serve` binds loopback and answers
# `GET /v1/verbs` — so HTTP is probed live rather than recorded ABSENT. The
# server is a child of this process and is killed on every exit path; a gate
# that leaks a listening socket has changed the machine it was auditing.
def free_port():
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


http_live, http_absent = set(), None
port = free_port()
srv = subprocess.Popen([BIN, "verb", "serve", "--port", str(port), "--bind", "127.0.0.1"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
try:
    deadline = time.time() + 30
    body = None
    while time.time() < deadline:
        if srv.poll() is not None:
            http_absent = f"`{BIN} verb serve` exited {srv.returncode} before it listened"
            break
        try:
            with urllib.request.urlopen(f"http://127.0.0.1:{port}/v1/verbs", timeout=2) as r:
                body = r.read().decode()
            break
        except (urllib.error.URLError, OSError):
            time.sleep(0.2)
    if body is None and http_absent is None:
        http_absent = f"`{BIN} verb serve --port {port}` never answered GET /v1/verbs"
    if body is not None:
        http_live = {v["name"] for v in json.loads(body).get("verbs", [])}
finally:
    srv.kill()
    srv.wait(timeout=30)

if http_absent is not None:
    rows.append(("http", "transport", "ABSENT", "no",
                 f"absent: {BIN} verb serve --port <p> && curl http://127.0.0.1:<p>/v1/verbs"))
else:
    for v in verbs:
        rows.append(("http", "verb", v, "yes", "yes" if v in http_live else "no"))
    for extra in sorted(http_live - set(verbs)):
        rows.append(("http", "verb", extra, "no", "yes"))

rows.sort()
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("transport,kind,name,declared,live\n")
    for r in rows:
        fh.write(",".join(r) + "\n")
PY

# ------------------------------------------------------------- vacuity floors
n_cli="$(awk -F, '$1=="cli"' "$derived" | wc -l)"
n_mcp="$(awk -F, '$1=="mcp" && $2=="tool"' "$derived" | wc -l)"
n_http="$(awk -F, '$1=="http" && $2=="verb"' "$derived" | wc -l)"
if [ "$n_cli" -lt "$MIN_CLI" ]; then
  fail "CLI surface fell to ${n_cli} names, floor is ${MIN_CLI} — a shrunken surface makes every agreement below cheap"
fi
if [ "$n_mcp" -lt "$MIN_MCP" ]; then
  fail "MCP surface fell to ${n_mcp} tools, floor is ${MIN_MCP} (a transport recorded ABSENT counts zero and is itself the finding)"
fi
if [ "$n_http" -lt "$MIN_HTTP" ]; then
  fail "HTTP surface fell to ${n_http} verbs, floor is ${MIN_HTTP} (a transport recorded ABSENT counts zero and is itself the finding)"
fi

# ------------------------------------------------- declared must equal live
mismatch="$(awk -F, 'NR>1 && $4!=$5 {print}' "$derived")"
if [ -n "$mismatch" ]; then
  printf '%s\n' "$mismatch"
  fail "$(printf '%s\n' "$mismatch" | wc -l) surface row(s) where declared != live — a promised capability the binary does not answer for, or one it answers for that nothing declares"
fi

# --------------------------------------------------- the committed snapshot
if [ "${FORJAR_DOGFOOD_WRITE:-0}" = "1" ]; then
  mkdir -p "$(dirname "$CSV")"
  cp "$derived" "$CSV"
  echo "GATE C PASS wrote ${CSV}: ${n_cli} CLI, ${n_mcp} MCP, ${n_http} HTTP"
  exit 0
fi

if [ ! -f "$CSV" ]; then
  fail "${CSV} is missing — regenerate it with FORJAR_DOGFOOD_WRITE=1 bash scripts/dogfood/surface.sh and commit it"
fi
if ! diff -u "$CSV" "$derived"; then
  fail "the shipped surface no longer matches ${CSV} (diff above) — if the change is intended, regenerate with FORJAR_DOGFOOD_WRITE=1 bash scripts/dogfood/surface.sh and commit"
fi

# ------------------------------------------------ CLI/MCP parity, on a fixture
#
# The set check above proves both transports LIST the verb. This proves they
# AGREE about one, on a config committed for the purpose: `validate` run three
# ways over tests/fixtures/dogfood/local-files.yaml must return the same
# verdict. #288's lesson is that listing is not answering.
FIXTURE="tests/fixtures/dogfood/local-files.yaml"
if [ ! -f "$FIXTURE" ]; then
  fail "${FIXTURE} is missing — the parity check below would have nothing to agree about"
fi
parity="$(
  python3 - "$BIN" "$FIXTURE" <<'PY'
import json, selectors, subprocess, sys, time
BIN, FIXTURE = sys.argv[1], sys.argv[2]


def mcp_call(binary, name, arguments, timeout=60):
    """`tools/call` over stdio. `forjar mcp` never exits on EOF — kill it."""
    init = {"jsonrpc": "2.0", "id": 1, "method": "initialize",
            "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                       "clientInfo": {"name": "forjar-dogfood", "version": "1"}}}
    call = {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
            "params": {"name": name, "arguments": arguments}}
    proc = subprocess.Popen([binary, "mcp"], stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                            text=True, bufsize=1)
    try:
        proc.stdin.write(json.dumps(init) + "\n" + json.dumps(call) + "\n")
        proc.stdin.flush()
        sel = selectors.DefaultSelector()
        sel.register(proc.stdout, selectors.EVENT_READ)
        deadline = time.time() + timeout
        while time.time() < deadline:
            if not sel.select(timeout=max(0.0, deadline - time.time())):
                continue
            line = proc.stdout.readline()
            if not line:
                return None
            try:
                msg = json.loads(line)
            except ValueError:
                continue
            if msg.get("id") == 2:
                # The verdict is the tool's own payload, which MCP wraps as a
                # TEXT BLOCK. Comparing `json.dumps(msg)` instead compares the
                # escaped form (`\"valid\":true`) and never matches, which
                # reads as "MCP disagrees" about a reply that agrees.
                blocks = msg.get("result", {}).get("content", [])
                return "".join(b.get("text", "") for b in blocks)
        return None
    finally:
        proc.kill()
        proc.wait(timeout=30)


cli = subprocess.run([BIN, "validate", "-f", FIXTURE], capture_output=True, text=True)
params = json.dumps({"path": FIXTURE})
verb = subprocess.run([BIN, "verb", "call", "validate", "--json", params],
                      capture_output=True, text=True)
mcp = mcp_call(BIN, "forjar_validate", {"path": FIXTURE})

def truthy(text):
    """Did this transport call the fixture valid?"""
    if not text:
        return False
    return ("\"valid\": true" in text) or ("\"valid\":true" in text) or text.startswith("OK:")

verdicts = {
    "cli": cli.returncode == 0 and truthy(cli.stdout.strip()),
    "verb": verb.returncode == 0 and truthy(verb.stdout),
    "mcp": truthy(mcp),
}
if len(set(verdicts.values())) != 1:
    print("DISAGREE " + json.dumps(verdicts))
elif not all(verdicts.values()):
    print("ALL-INVALID " + json.dumps(verdicts))
else:
    print("AGREE")
PY
)"
case "$parity" in
  AGREE) : ;;
  ALL-INVALID*) fail "every transport calls ${FIXTURE} invalid — they agree, but about a fixture that no longer parses, which would let them agree forever: ${parity}" ;;
  *) fail "CLI, verb and MCP disagree about ${FIXTURE}: ${parity}" ;;
esac

echo "GATE C PASS ${n_cli} CLI name(s), ${n_mcp} MCP tool(s), ${n_http} HTTP verb(s); every declared name is live and every live name declared; matches ${CSV}; CLI/verb/MCP agree on the fixture"

# mutation: raise MIN_CLI to 9999 — the vacuity floor then rejects the real
# 211-name surface and the gate exits 1. (The behavioural mutation: delete a
# line from docs/audits/surface_audit.csv and the snapshot diff fails.)
