# Generated by forjar dist (do not edit)
Name:    forjar
Version: VERSION
Release: 1
Summary: Rust-native Infrastructure as Code
License: MIT OR Apache-2.0
URL:     https://forjar.dev
Source0: forjar-{version}-x86_64-unknown-linux-gnu.tar.gz

%description
Rust-native Infrastructure as Code

%install
mkdir -p %{buildroot}/usr/local/bin
cp forjar %{buildroot}/usr/local/bin/

%files
/usr/local/bin/forjar
