# Generated by forjar dist (do not edit)
class Forjar < Formula
  desc "Rust-native Infrastructure as Code"
  homepage "https://forjar.dev"
  license "MIT OR Apache-2.0"
  version "VERSION"

  on_linux do
    on_intel do
      url "https://github.com/paiml/forjar/releases/download/v#{version}/forjar-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_CHECKSUM"
    end
    on_arm do
      url "https://github.com/paiml/forjar/releases/download/v#{version}/forjar-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_CHECKSUM"
    end
  end

  on_macos do
    on_intel do
      url "https://github.com/paiml/forjar/releases/download/v#{version}/forjar-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_CHECKSUM"
    end
    on_arm do
      url "https://github.com/paiml/forjar/releases/download/v#{version}/forjar-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_CHECKSUM"
    end
  end


  def install
    bin.install "forjar"
  end

  def caveats
    <<~EOS
      To get started, run:
  forjar init
    EOS
  end

  test do
    assert_match "forjar", shell_output("#{bin}/forjar --version")
  end
end
