//! Generate shell scripts for different resource types.
//!
//! Usage: cargo run --example codegen_scripts

use forjar::core::codegen;
use forjar::core::types::{MachineTarget, Resource, ResourceType};

fn main() {
    println!("=== Package Resource (apt) ===\n");
    let pkg = Resource {
        resource_type: ResourceType::Package,
        machine: MachineTarget::Single("local".to_string()),
        state: None,
        depends_on: vec![],
        provider: Some("apt".to_string()),
        packages: vec!["curl".to_string(), "htop".to_string()],
        version: None,
        path: None,
        content: None,
        source: None,
        target: None,
        owner: None,
        group: None,
        mode: None,
        name: None,
        enabled: None,
        restart_on: vec![],
        fs_type: None,
        options: None,
        uid: None,
        shell: None,
        home: None,
        groups: vec![],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: None,
        command: None,
        image: None,
        ports: vec![],
        environment: vec![],
        volumes: vec![],
        restart: None,
        protocol: None,
        port: None,
        action: None,
        from_addr: None,
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Check script --");
    println!("{}", codegen::check_script(&pkg).unwrap());
    println!("\n-- Apply script --");
    println!("{}", codegen::apply_script(&pkg).unwrap());
    println!("\n-- State query script --");
    println!("{}", codegen::state_query_script(&pkg).unwrap());

    println!("\n=== File Resource ===\n");
    let file = Resource {
        resource_type: ResourceType::File,
        machine: MachineTarget::Single("local".to_string()),
        state: None,
        depends_on: vec![],
        provider: None,
        packages: vec![],
        version: None,
        path: Some("/etc/app/config.yaml".to_string()),
        content: Some("database:\n  host: localhost\n  port: 5432\n".to_string()),
        source: None,
        target: None,
        owner: Some("app".to_string()),
        group: Some("app".to_string()),
        mode: Some("0640".to_string()),
        name: None,
        enabled: None,
        restart_on: vec![],
        fs_type: None,
        options: None,
        uid: None,
        shell: None,
        home: None,
        groups: vec![],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: None,
        command: None,
        image: None,
        ports: vec![],
        environment: vec![],
        volumes: vec![],
        restart: None,
        protocol: None,
        port: None,
        action: None,
        from_addr: None,
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Apply script --");
    println!("{}", codegen::apply_script(&file).unwrap());

    println!("\n=== File Resource (source transfer) ===\n");
    let source_file = Resource {
        resource_type: ResourceType::File,
        machine: MachineTarget::Single("local".to_string()),
        state: None,
        depends_on: vec![],
        provider: None,
        packages: vec![],
        version: None,
        path: Some("/opt/app/entrypoint.sh".to_string()),
        content: None,
        source: Some("examples/files/app-entrypoint.sh".to_string()),
        target: None,
        owner: Some("app".to_string()),
        group: None,
        mode: Some("0755".to_string()),
        name: None,
        enabled: None,
        restart_on: vec![],
        fs_type: None,
        options: None,
        uid: None,
        shell: None,
        home: None,
        groups: vec![],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: None,
        command: None,
        image: None,
        ports: vec![],
        environment: vec![],
        volumes: vec![],
        restart: None,
        protocol: None,
        port: None,
        action: None,
        from_addr: None,
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Apply script (base64 transfer) --");
    println!("{}", codegen::apply_script(&source_file).unwrap());

    println!("\n=== Service Resource ===\n");
    let svc = Resource {
        resource_type: ResourceType::Service,
        machine: MachineTarget::Single("local".to_string()),
        state: Some("running".to_string()),
        depends_on: vec![],
        provider: None,
        packages: vec![],
        version: None,
        path: None,
        content: None,
        source: None,
        target: None,
        owner: None,
        group: None,
        mode: None,
        name: Some("nginx".to_string()),
        enabled: Some(true),
        restart_on: vec![],
        fs_type: None,
        options: None,
        uid: None,
        shell: None,
        home: None,
        groups: vec![],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: None,
        command: None,
        image: None,
        ports: vec![],
        environment: vec![],
        volumes: vec![],
        restart: None,
        protocol: None,
        port: None,
        action: None,
        from_addr: None,
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Apply script --");
    println!("{}", codegen::apply_script(&svc).unwrap());

    println!("\n=== Mount Resource (NFS) ===\n");
    let mnt = Resource {
        resource_type: ResourceType::Mount,
        machine: MachineTarget::Single("local".to_string()),
        state: None,
        depends_on: vec![],
        provider: None,
        packages: vec![],
        version: None,
        path: Some("/mnt/data".to_string()),
        content: None,
        source: Some("192.168.1.10:/exports/data".to_string()),
        target: None,
        owner: None,
        group: None,
        mode: None,
        name: None,
        enabled: None,
        restart_on: vec![],
        fs_type: Some("nfs".to_string()),
        options: Some("ro,hard,intr".to_string()),
        uid: None,
        shell: None,
        home: None,
        groups: vec![],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: None,
        command: None,
        image: None,
        ports: vec![],
        environment: vec![],
        volumes: vec![],
        restart: None,
        protocol: None,
        port: None,
        action: None,
        from_addr: None,
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Apply script --");
    println!("{}", codegen::apply_script(&mnt).unwrap());

    println!("\n=== User Resource ===\n");
    let usr = Resource {
        resource_type: ResourceType::User,
        machine: MachineTarget::Single("local".to_string()),
        state: None,
        depends_on: vec![],
        provider: None,
        packages: vec![],
        version: None,
        path: None,
        content: None,
        source: None,
        target: None,
        owner: None,
        group: None,
        mode: None,
        name: Some("deploy".to_string()),
        enabled: None,
        restart_on: vec![],
        fs_type: None,
        options: None,
        uid: None,
        shell: Some("/bin/bash".to_string()),
        home: Some("/home/deploy".to_string()),
        groups: vec!["docker".to_string(), "sudo".to_string()],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: None,
        command: None,
        image: None,
        ports: vec![],
        environment: vec![],
        volumes: vec![],
        restart: None,
        protocol: None,
        port: None,
        action: None,
        from_addr: None,
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Check script --");
    println!("{}", codegen::check_script(&usr).unwrap());
    println!("\n-- Apply script --");
    println!("{}", codegen::apply_script(&usr).unwrap());

    println!("\n=== Docker Resource ===\n");
    let docker = Resource {
        resource_type: ResourceType::Docker,
        machine: MachineTarget::Single("local".to_string()),
        state: Some("running".to_string()),
        depends_on: vec![],
        provider: None,
        packages: vec![],
        version: None,
        path: None,
        content: None,
        source: None,
        target: None,
        owner: None,
        group: None,
        mode: None,
        name: Some("web".to_string()),
        enabled: None,
        restart_on: vec![],
        fs_type: None,
        options: None,
        uid: None,
        shell: None,
        home: None,
        groups: vec![],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: None,
        command: None,
        image: Some("nginx:latest".to_string()),
        ports: vec!["8080:80".to_string()],
        environment: vec!["ENV=production".to_string()],
        volumes: vec![],
        restart: Some("unless-stopped".to_string()),
        protocol: None,
        port: None,
        action: None,
        from_addr: None,
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Apply script --");
    println!("{}", codegen::apply_script(&docker).unwrap());

    println!("\n=== Cron Resource ===\n");
    let cron = Resource {
        resource_type: ResourceType::Cron,
        machine: MachineTarget::Single("local".to_string()),
        state: None,
        depends_on: vec![],
        provider: None,
        packages: vec![],
        version: None,
        path: None,
        content: None,
        source: None,
        target: None,
        owner: Some("root".to_string()),
        group: None,
        mode: None,
        name: Some("db-backup".to_string()),
        enabled: None,
        restart_on: vec![],
        fs_type: None,
        options: None,
        uid: None,
        shell: None,
        home: None,
        groups: vec![],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: Some("0 2 * * *".to_string()),
        command: Some("/opt/scripts/backup-db.sh".to_string()),
        image: None,
        ports: vec![],
        environment: vec![],
        volumes: vec![],
        restart: None,
        protocol: None,
        port: None,
        action: None,
        from_addr: None,
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Apply script --");
    println!("{}", codegen::apply_script(&cron).unwrap());

    println!("\n=== Network Resource (ufw) ===\n");
    let fw = Resource {
        resource_type: ResourceType::Network,
        machine: MachineTarget::Single("local".to_string()),
        state: None,
        depends_on: vec![],
        provider: None,
        packages: vec![],
        version: None,
        path: None,
        content: None,
        source: None,
        target: None,
        owner: None,
        group: None,
        mode: None,
        name: Some("ssh-access".to_string()),
        enabled: None,
        restart_on: vec![],
        fs_type: None,
        options: None,
        uid: None,
        shell: None,
        home: None,
        groups: vec![],
        ssh_authorized_keys: vec![],
        system_user: false,
        schedule: None,
        command: None,
        image: None,
        ports: vec![],
        environment: vec![],
        volumes: vec![],
        restart: None,
        protocol: Some("tcp".to_string()),
        port: Some("22".to_string()),
        action: Some("allow".to_string()),
        from_addr: Some("10.0.0.0/8".to_string()),
        recipe: None,
        inputs: std::collections::HashMap::new(),
        arch: vec![],
        tags: vec![],
        when: None,
        chroot_dir: None,
        namespace_uid: None,
        namespace_gid: None,
        seccomp: false,
        netns: false,
        cpuset: None,
        memory_limit: None,
        overlay_lower: None,
        overlay_upper: None,
        overlay_work: None,
        overlay_merged: None,
    };

    println!("-- Apply script --");
    println!("{}", codegen::apply_script(&fw).unwrap());
}
