use super::*;
use crate::core::types::MachineTarget;
use std::collections::HashMap;

pub(super) fn make_config() -> ForjarConfig {
let yaml = "\nversion: \"1.0\"\nname: test\nmachines:\n  m1:\n    hostname: m1\n    addr: 127.0.0.1\nresources:\n  pkg:\n    type: package\n    machine: m1\n    provider: apt\n    packages: [curl]\n  conf:\n    type: file\n    machine: m1\n    path: /etc/test.conf\n    content: \"hello\"\n    depends_on: [pkg]\n  svc:\n    type: service\n    machine: m1\n    name: nginx\n    state: running\n    depends_on: [conf]\n";
serde_yaml_ng::from_str(yaml).unwrap()
}

pub(super) fn make_base_resource(rt: ResourceType) -> Resource {
Resource {
    resource_type: rt,
    machine: MachineTarget::Single("m1".to_string()),
    state: None,
    depends_on: vec![],
    provider: None,
    packages: vec![],
    version: None,
    path: None,
    content: None,
    source: None,
    target: None,
    owner: None,
    group: None,
    mode: None,
    name: None,
    enabled: None,
    restart_on: vec![],
    triggers: vec![],
    fs_type: None,
    options: None,
    uid: None,
    shell: None,
    home: None,
    groups: vec![],
    ssh_authorized_keys: vec![],
    system_user: false,
    schedule: None,
    command: None,
    image: None,
    ports: vec![],
    environment: vec![],
    volumes: vec![],
    restart: None,
    protocol: None,
    port: None,
    action: None,
    from_addr: None,
    recipe: None,
    inputs: HashMap::new(),
    arch: vec![],
    tags: vec![],
    resource_group: None,
    when: None,
    count: None,
    for_each: None,
    chroot_dir: None,
    namespace_uid: None,
    namespace_gid: None,
    seccomp: false,
    netns: false,
    cpuset: None,
    memory_limit: None,
    overlay_lower: None,
    overlay_upper: None,
    overlay_work: None,
    overlay_merged: None,
    format: None,
    quantization: None,
    checksum: None,
    cache_dir: None,
    gpu_backend: None,
    driver_version: None,
    cuda_version: None,
    rocm_version: None,
    devices: vec![],
    persistence_mode: None,
    compute_mode: None,
    gpu_memory_limit_mb: None,
    pre_apply: None,
    post_apply: None,
}
}
